// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/background_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackgroundService_BackgroundCreate_FullMethodName = "/proto.BackgroundService/BackgroundCreate"
)

// BackgroundServiceClient is the client API for BackgroundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackgroundServiceClient interface {
	BackgroundCreate(ctx context.Context, in *BackgroundCreateRequest, opts ...grpc.CallOption) (*BackgroundCreateResponse, error)
}

type backgroundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackgroundServiceClient(cc grpc.ClientConnInterface) BackgroundServiceClient {
	return &backgroundServiceClient{cc}
}

func (c *backgroundServiceClient) BackgroundCreate(ctx context.Context, in *BackgroundCreateRequest, opts ...grpc.CallOption) (*BackgroundCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackgroundCreateResponse)
	err := c.cc.Invoke(ctx, BackgroundService_BackgroundCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackgroundServiceServer is the server API for BackgroundService service.
// All implementations must embed UnimplementedBackgroundServiceServer
// for forward compatibility.
type BackgroundServiceServer interface {
	BackgroundCreate(context.Context, *BackgroundCreateRequest) (*BackgroundCreateResponse, error)
	mustEmbedUnimplementedBackgroundServiceServer()
}

// UnimplementedBackgroundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackgroundServiceServer struct{}

func (UnimplementedBackgroundServiceServer) BackgroundCreate(context.Context, *BackgroundCreateRequest) (*BackgroundCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackgroundCreate not implemented")
}
func (UnimplementedBackgroundServiceServer) mustEmbedUnimplementedBackgroundServiceServer() {}
func (UnimplementedBackgroundServiceServer) testEmbeddedByValue()                           {}

// UnsafeBackgroundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackgroundServiceServer will
// result in compilation errors.
type UnsafeBackgroundServiceServer interface {
	mustEmbedUnimplementedBackgroundServiceServer()
}

func RegisterBackgroundServiceServer(s grpc.ServiceRegistrar, srv BackgroundServiceServer) {
	// If the following call pancis, it indicates UnimplementedBackgroundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackgroundService_ServiceDesc, srv)
}

func _BackgroundService_BackgroundCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackgroundCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackgroundServiceServer).BackgroundCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackgroundService_BackgroundCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackgroundServiceServer).BackgroundCreate(ctx, req.(*BackgroundCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackgroundService_ServiceDesc is the grpc.ServiceDesc for BackgroundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackgroundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BackgroundService",
	HandlerType: (*BackgroundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BackgroundCreate",
			Handler:    _BackgroundService_BackgroundCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/background_service.proto",
}
